#!/usr/bin/env python3

import logging
import os
import shutil
import sys
import tarfile
from argparse import ArgumentParser
from os import path as osp

py_version = sys.version_info[0]
if py_version != 3:
    print("Python %s is not supported." % py_version)
    sys.exit(1)

LOG_LEVEL = 'INFO'
ANSIBLE_PORTABLE_VERSION = 'v0.4.1'

logging.basicConfig(format='%(asctime)s [%(levelname)s]: %(message)s', stream=sys.stdout, level=LOG_LEVEL)
logger = logging.getLogger()

URL_TEMPLATE = 'https://github.com/ownport/portable-ansible/releases/download/%(version)s/portable-ansible-%(version)s-py3.tar.bz2'

SCRIPT_DIR = osp.dirname(osp.realpath(sys.argv[0]))
BASE_DIR = osp.join(SCRIPT_DIR, '.blew')
ANSIBLE = 'ansible'
ANSIBLE_DIR = osp.join(BASE_DIR, ANSIBLE)
EXEC = 'exec'
EXEC_DIR = osp.join(BASE_DIR, EXEC)
BIN = 'bin'
BIN_DIR = osp.join(BASE_DIR, BIN)

SCRIPT_TEMPLATE = """\
#!/usr/bin/env bash
python3 $(dirname $0)/../%(exec)s/%(command)s $@
"""

COMMANDS = (
    'ansible',
    'ansible-config',
    'ansible-connection',
    'ansible-console',
    'ansible-doc',
    'ansible-galaxy',
    'ansible-inventory',
    'ansible-lint',
    'ansible-playbook',
    'ansible-pull',
    'ansible-test',
    'ansible-vault'
)


def safe_remove_dir(path):
    if osp.exists(path):
        logger.debug('Removing %s.', path)
        shutil.rmtree(path)
    else:
        logger.debug('%s does not exist.', path)


def prepare_dir(path, force_empty=False):
    from pathlib import Path
    if force_empty:
        safe_remove_dir(path)
    logger.debug("Preparing dir %s.", path)
    Path(path).mkdir(parents=True, exist_ok=True)
    return path


def build(ansible_portable_version):
    from urllib.request import urlretrieve
    safe_remove_dir(BASE_DIR)
    url = URL_TEMPLATE % {'version': ansible_portable_version}
    logger.info('Downloading %s.', url)
    with tarfile.open(urlretrieve(url, filename=None)[0]) as tar:
        logger.info('Extracting portable-ansible version %s to %s.', ansible_portable_version, BASE_DIR)
        tar.extractall(BASE_DIR)
    prepare_dir(EXEC_DIR)
    prepare_dir(BIN_DIR)
    for command in COMMANDS:
        os.symlink(osp.join(osp.pardir, ANSIBLE), osp.join(EXEC_DIR, command), True)
        script = osp.join(BIN_DIR, command)
        with open(script, 'w') as w:
            w.write(SCRIPT_TEMPLATE % {'command': command, 'exec': EXEC})
        os.chmod(script, 0o755)


def get_parser():
    parser = ArgumentParser(osp.basename(sys.argv[0]), add_help=False)
    parser.add_argument('--log-level', default='INFO')
    parser.add_argument('--blew-help', action='store_true')
    parser.set_defaults(command='ansible')
    subparsers = parser.add_subparsers()
    for command in COMMANDS:
        if command.startswith('ansible-'):
            subparser = subparsers.add_parser(command[8:], add_help=False)
            subparser.set_defaults(command=command)
    parser_reset = subparsers.add_parser('reset', description="Initialize or re-initialize .blew directory.")
    parser_reset.set_defaults(command='reset')
    return parser


if __name__ == '__main__':
    parser = get_parser()
    args, extra_args = parser.parse_known_args()
    logger.setLevel(args.log_level.upper())
    if args.blew_help:
        parser.print_help()
        sys.exit(0)
    if not osp.exists(BASE_DIR) or args.command == 'reset':
        build(ANSIBLE_PORTABLE_VERSION)
    if args.command in COMMANDS:
        from subprocess import run

        process = run([osp.join(BIN_DIR, args.command)] + extra_args)
        sys.exit(process.returncode)
